# Generated by Django 3.2.8 on 2021-10-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_dependants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependants',
            name='principal_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='principal.principal'),
        ),
    ]
